services:
  postgres:
    image: postgres:16
    container_name: quita-postgres

    environment:
      POSTGRES_DB: quita_db
      POSTGRES_USER: quita_user
      POSTGRES_PASSWORD: quita_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
