spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: INFO
