package com.quita.api.payment.model;

public enum PaymentEventType {
    PAYMENT_CREATED,
    WEBHOOK_RECEIVED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_CANCELLED,
    PAYMENT_PENDING,
    RECONCILIATION_EXECUTED,
    RECONCILIATION_APPROVED,
    CREDITS_GRANTED,
    DUPLICATE_WEBHOOK_IGNORED
}
